/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we want to create a custom sidebar
  docsSidebar: [
    'intro', // Points to docs/intro.md
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/setup', // Points to docs/getting-started/setup.md
        'getting-started/basic-usage', // Points to docs/getting-started/basic-usage.md
      ],
    },
    {
      type: 'category',
      label: 'Use AIOHA',
      link: {
        type: 'doc',
        id: 'use-aioha',
      },
      items: [
        'use-aioha#authentication',
        'use-aioha#user-management',
        'use-aioha#onchain-operations',
        'use-aioha#helpers',
      ],
    },
    'use-dhive',
    'extra-utilities',
    // Example for a future "Guides" section
    // {
    //   type: 'category',
    //   label: 'Guides',
    //   items: ['guides/some-guide'], // Points to docs/guides/some-guide.md
    // },
  ],
};

module.exports = sidebars;
